<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ReportFromExcelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('reports')->insert([
            // ==================== INCIDENT ====================
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00001',
                'requestor'         => 'Aldian Prawira',
                'requestor_email'   => 'aldian.prawira@lintasarta.co.id',
                'request_date'      => '2026-03-01',
                'report_time'       => '22:00:00',
                'apps'              => 'B2B Portal',
                'type'              => 'Incident',
                'description'       => '502 Bad gateway',
                'severity'          => '1 - Emergency (Full Down)',
                'assigned_to'       => 'Application Owner (L3)',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'hardware issues affecting VM, auto start mechanism after restart is applied to the LB service (php - fpm)',
                'rca'               => null,
                'created_at'        => '2026-03-01 22:42:01',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00002',
                'requestor'         => 'Hanafi Husnipradja',
                'requestor_email'   => 'hanafi.husnipradja@lintasarta.co.id',
                'request_date'      => '2026-03-02',
                'report_time'       => '20:06:00',
                'apps'              => 'SQA Portal',
                'type'              => 'Incident',
                'description'       => 'SQA portal service was down at 20.06 WIB',
                'severity'          => '1 - Emergency (Full Down)',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Infrastructure',
                'status'            => 0,
                'resolution'        => 'The service went down because an unexpected restart to designated Virtual Machine.',
                'rca'               => null,
                'created_at'        => '2026-03-02 20:12:32',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00003',
                'requestor'         => 'ICT Indosat',
                'requestor_email'   => 'ict.service@ioh.co.id',
                'request_date'      => '2026-03-05',
                'report_time'       => '09:50:00',
                'apps'              => 'SARAS',
                'type'              => 'Incident',
                'description'       => 'Signal from trigger does not sync with alarm on customer site',
                'severity'          => '3 - Major',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Third Party',
                'status'            => 0,
                'resolution'        => 'The Alarm signal was not synchronized because the device was not active.',
                'rca'               => null,
                'created_at'        => '2026-03-09 10:11:33',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00004',
                'requestor'         => 'Refky',
                'requestor_email'   => 'MuhammadRefky.HikmaSanjaya@TechMahindra.com',
                'request_date'      => '2026-03-07',
                'report_time'       => '10:00:00',
                'apps'              => 'B2B Portal',
                'type'              => 'Incident',
                'description'       => 'user ods bot suffer long load time to access windows shopping leased line on CO portal via b2b portal',
                'severity'          => '4 - Minor',
                'assigned_to'       => 'Application Owner (L3)',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'It was discovered that the Application Owner used a different navigation path.',
                'rca'               => null,
                'created_at'        => '2026-03-11 10:29:49',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00005',
                'requestor'         => 'Yogi Hardiansyah',
                'requestor_email'   => 'muhammad.ardiansyah@ioh.co.id',
                'request_date'      => '2026-03-12',
                'report_time'       => '10:25:00',
                'apps'              => 'SARAS',
                'type'              => 'Incident',
                'description'       => 'BANK DKI Branch alert did not sync with device and SARAS',
                'severity'          => '3 - Major (Partial Issue)',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'Signal interference affecting synchronization.',
                'rca'               => null,
                'created_at'        => '2026-03-17 10:32:39',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00006',
                'requestor'         => 'Aldian Prawira',
                'requestor_email'   => 'aldianprawira99@gmail.com',
                'request_date'      => '2026-04-18',
                'report_time'       => '20:00:00',
                'apps'              => 'SQA Portal',
                'type'              => 'Incident',
                'description'       => 'SQA Portal Down',
                'severity'          => '1 - Emergency (Full Down)',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'VM restarted unexpectedly.',
                'rca'               => null,
                'created_at'        => '2026-04-06 20:15:07',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00007',
                'requestor'         => 'Hanafi',
                'requestor_email'   => 'hanafi.husnipradja@lintasarta.co.id',
                'request_date'      => '2026-04-29',
                'report_time'       => '03:24:00',
                'apps'              => 'MPR',
                'type'              => 'Incident',
                'description'       => '504 Gateway timeout',
                'severity'          => '4 - Minor',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'Dependencies error on php modules.',
                'rca'               => null,
                'created_at'        => '2026-04-17 03:28:05',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00008',
                'requestor'         => 'Hanafi Husnipradja',
                'requestor_email'   => 'hanafi.husnipradja@lintasarta.co.id',
                'request_date'      => '2026-04-13',
                'report_time'       => '15:00:00',
                'apps'              => 'DBEST',
                'type'              => 'Incident',
                'description'       => '500 - Internal server error',
                'severity'          => '4 - Minor',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'application requests attempted to load dependency files while the system was in a transitional state.',
                'rca'               => null,
                'created_at'        => '2026-04-21 12:15:43',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00009',
                'requestor'         => 'Hanafi Husnipradja',
                'requestor_email'   => 'hanafi.husnipradja@lintasarta.co.id',
                'request_date'      => '2026-05-03',
                'report_time'       => '00:37:00',
                'apps'              => 'SARAS',
                'type'              => 'Incident',
                'description'       => 'SARAS unreachable - 502 Bad Gateway',
                'severity'          => '4 - Minor',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'Waiting for GCP access',
                'rca'               => null,
                'created_at'        => '2026-05-03 00:40:16',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00010',
                'requestor'         => 'Aldian Prawira',
                'requestor_email'   => 'aldian.prawira@lintasarta.co.id',
                'request_date'      => '2026-04-23',
                'report_time'       => '05:15:00',
                'apps'              => 'My Dashboard',
                'type'              => 'Incident',
                'description'       => 'Intermittent error code 500, 502 on MyDashboard apps',
                'severity'          => '4 - Minor',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'Failed to connect to third party services, oauth0.com',
                'rca'               => null,
                'created_at'        => '2026-04-11 05:20:55',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00011',
                'requestor'         => 'Hanafi H',
                'requestor_email'   => 'hanafi.husnipradja@lintasarta.co.id',
                'request_date'      => '2026-05-19',
                'report_time'       => '08:45:00',
                'apps'              => 'My Dashboard',
                'type'              => 'Incident',
                'description'       => '502 bad gateway and 503 service unavailable on 2nd redirects',
                'severity'          => '4 - Minor',
                'assigned_to'       => 'B2B Applications Operations',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'Network Issue on auth0 3rd party services',
                'rca'               => null,
                'created_at'        => '2026-05-07 08:43:54',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'INC00012',
                'requestor'         => 'Hanafi Husnipradja',
                'requestor_email'   => 'hanafi.husnipradja@lintasarta.co.id',
                'request_date'      => '2026-05-15',
                'report_time'       => '15:30:00',
                'apps'              => 'DBEST',
                'type'              => 'Incident',
                'description'       => 'ES ODS bot get 500 internal server error',
                'severity'          => '4 - Minor',
                'assigned_to'       => 'Application Owner (L3)',
                'scope'             => 'Application Bug',
                'status'            => 0,
                'resolution'        => 'False mechanism on handling data leaks on users table.',
                'rca'               => null,
                'created_at'        => '2026-05-13 15:33:38',
                'updated_at'        => now(),
            ],

            // ==================== REQUEST ====================
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00001',
                'requestor'         => 'Diki Iskandar',
                'requestor_email'   => 'dikiiskandar@ioh.co.id',
                'request_date'      => '2026-02-18',
                'report_time'       => '11:09:00',
                'apps'              => 'My Dashboard',
                'type'              => 'Request',
                'description'       => 'myDashboard integration with Privy (Staging) for Indirect Channel 0.5 development needs',
                'severity'          => '3 - Low',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Third Party',
                'status'            => 1,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-02-19 11:34:08',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00002',
                'requestor'         => 'Raras Wirasto',
                'requestor_email'   => 'raras.wirasto@ioh.co.id',
                'request_date'      => '2026-02-12',
                'report_time'       => '10:00:00',
                'apps'              => 'DBEST',
                'type'              => 'Request',
                'description'       => 'ES Automation on DBEST. ES Group will initiate an Automation use case which involved the Desk Survey & Pricing Scope on the dbest web application. UIPATH',
                'severity'          => '3 - Low',
                'assigned_to'       => 'App Owner',
                'scope'             => 'Third Party',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-02-20 10:27:01',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00003',
                'requestor'         => 'Relly Suwandana Agung Setyo',
                'requestor_email'   => 'r.setyo@ioh.co.id',
                'request_date'      => '2026-02-23',
                'report_time'       => '22:00:00',
                'apps'              => 'DBEST',
                'type'              => 'Request',
                'description'       => 'Update certificate',
                'severity'          => '3 - Medium (Partial Issue)',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Update certificate',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-02-23 22:35:30',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00004',
                'requestor'         => 'Raras Wirasto',
                'requestor_email'   => 'raras.wirasto@ioh.co.id',
                'request_date'      => '2026-03-02',
                'report_time'       => '10:38:00',
                'apps'              => 'B2B Portal',
                'type'              => 'Request',
                'description'       => 'Request to create user for ES ODS automation',
                'severity'          => '3 - Low',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Create user',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-03-03 10:55:03',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00005',
                'requestor'         => 'Raras Wirasto',
                'requestor_email'   => 'raras.wirasto@ioh.co.id',
                'request_date'      => '2026-03-02',
                'report_time'       => '10:38:00',
                'apps'              => 'DBEST',
                'type'              => 'Request',
                'description'       => 'Creating user for ES ODS Automation initiative',
                'severity'          => '3 - Low',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Create user',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-03-03 10:55:58',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00006',
                'requestor'         => 'Aldian Prawira',
                'requestor_email'   => 'aldian.prawira@lintasarta.co.id',
                'request_date'      => '2026-03-06',
                'report_time'       => '11:35:00',
                'apps'              => 'DBEST',
                'type'              => 'Request',
                'description'       => 'Create user super admin on DBEST for B2B ops',
                'severity'          => '3 - Low',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Create User',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-03-06 11:36:24',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00007',
                'requestor'         => 'Ady Wisma Putra Wardana',
                'requestor_email'   => 'Ady Wisma Putra Wardana',
                'request_date'      => '2026-03-10',
                'report_time'       => '09:40:00',
                'apps'              => 'SQA Portal',
                'type'              => 'Request',
                'description'       => 'Patching for Windows Server 2012 R2 - SQA Portal server',
                'severity'          => '3 - Low',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Infrastructure',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-03-17 09-55-39',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00008',
                'requestor'         => 'Relly Suwandana Agung Setyo',
                'requestor_email'   => 'r.setyo@ioh.co.id',
                'request_date'      => '2026-04-02',
                'report_time'       => '14:25:00',
                'apps'              => 'DBEST',
                'type'              => 'Request',
                'description'       => 'Request to create ARS for development and staging environments',
                'severity'          => '3 - Low',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Create ARS',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-04-02 14:28:54',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00009',
                'requestor'         => 'Aldian',
                'requestor_email'   => 'aldian.prawira@lintasarta.co.id',
                'request_date'      => '2026-04-20',
                'report_time'       => '16:34:00',
                'apps'              => 'My Dashboard',
                'type'              => 'Request',
                'description'       => 'Restarting nginx on VM Web App 2',
                'severity'          => '3 - Low',
                'assigned_to'       => 'App Owner',
                'scope'             => 'Infrastructure',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-04-20 16:35:22',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00010',
                'requestor'         => 'Hanafi',
                'requestor_email'   => 'hanafi.husnipradja@lintasarta.co.id',
                'request_date'      => '2026-05-12',
                'report_time'       => '22:00:00',
                'apps'              => 'IOT Middleware TJ',
                'type'              => 'Request',
                'description'       => 'IOT Middleware Update VSS driver',
                'severity'          => '3 - Low',
                'assigned_to'       => 'App Owner',
                'scope'             => 'Update',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-05-12 22:17:45',
                'updated_at'        => now(),
            ],
            [
                'uuid'              => Str::uuid(),
                'incident'          => 'REQ00011',
                'requestor'         => 'Aldian Prawira',
                'requestor_email'   => 'aldian.prawira@lintasarta.co.id',
                'request_date'      => '2026-05-14',
                'report_time'       => '16:12:00',
                'apps'              => 'IOT Middleware TJ',
                'type'              => 'Request',
                'description'       => 'Device IMEI replacement for mikrotrans fleet KLM 220022',
                'severity'          => '3 - Low',
                'assigned_to'       => 'B2B Apps Ops Support',
                'scope'             => 'Add imei',
                'status'            => 0,
                'resolution'        => null,
                'rca'               => null,
                'created_at'        => '2026-05-14 16:51:43',
                'updated_at'        => now(),
            ],
        ]);

        $this->command->info('✅ ReportFromExcelSeeder berhasil dijalankan. Total 12 Incident + 11 Request telah diimport.');
    }
}